FROM docker.io/opsmx11/echo:custnotification
MAINTAINER sig-platform@spinnaker.io
COPY echo-web/build/install/echo /opt/echo
USER root
RUN apt-get update
RUN apt-get install -y wget curl vim net-tools nettle-dev
RUN mkdir -p /opt/echo/plugins
ARG CUSTOMPLUGIN_RELEASEVERSION
ENV CUSTOMPLUGIN_RELEASEVERSION=$CUSTOMPLUGIN_RELEASEVERSION
RUN wget -O Opsmx.EchoEventPlugin-EchoEventPlugin-v1.0.1-SNAPSHOT.zip -c https://github.com/OpsMx/Customplugins/releases/download/${CUSTOMPLUGIN_RELEASEVERSION}/EchoEventPlugin-v1.0.1-SNAPSHOT.zip -P /opt/echo/plugins
RUN mv Opsmx.EchoEventPlugin-EchoEventPlugin-v1.0.1-SNAPSHOT.zip /opt/echo/plugins/
RUN chmod -R 777 /opt/echo/plugins/
USER spinnaker
CMD ["/opt/echo/bin/echo"]
