FROM docker.io/opsmx11/echo:custnotification
MAINTAINER sig-platform@spinnaker.io
COPY echo-web/build/install/echo /opt/echo
USER root
RUN apt-get -y install  wget 
RUN apt-get -y install  curl
RUN apt-get -y install  vim
RUN apt-get update && apt-get -y install openjdk-8-jre-headless
USER spinnaker
RUN adduser --disabled-login --system spinnaker
RUN mkdir -p /opt/echo/plugins && chown -R spinnaker:nogroup /opt/echo/plugins
CMD ["/opt/echo/bin/echo"]
