FROM docker.io/opsmx11/echo:custnotification
MAINTAINER sig-platform@spinnaker.io
COPY echo-web/build/install/echo /opt/echo
RUN apt-get update && apt-get -y install openjdk-8-jre-headless wget vim  net-tools curl
RUN adduser --disabled-login --system spinnaker
RUN mkdir -p /opt/echo/plugins && chown -R spinnaker:nogroup /opt/echo/plugins
USER spinnaker
CMD ["/opt/echo/bin/echo"]
