FROM quay.io/opsmxpublic/ubifips:8.7
MAINTAINER sig-platform@spinnaker.io
COPY echo-web/build/install/echo /opt/echo
RUN yum -y install java-11-openjdk-devel wget vim curl net-tools nettle
RUN yum -y update
RUN adduser spinnaker
ENV SERVICE_PLUGIN_PATH=/opt/echo/plugins
RUN mkdir -p ${SERVICE_PLUGIN_PATH}



RUN chmod -R 777 ${SERVICE_PLUGIN_PATH}
RUN chown -R spinnaker:spinnaker /opt/
USER spinnaker
CMD ["/opt/echo/bin/echo"]
