
name: echo 1.28.4 build
on:
 push:
    branches:
    - 'v2.34.4-1.28.4-mar20-23'
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g
  CONTAINER_REGISTRY: quay.io/opsmxpublic
jobs:
  build-echo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout echo repo
      uses: actions/checkout@v3
      ###with:
        #repository: opsmx/echo
        #ref: refs/heads/master
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
        cache: 'gradle'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Prepare build variables
      id: build_variables
      run: |
          echo ::set-output name=REPO::"ubi8-oes-echo"
          echo ::set-output name=VERSION::"1.28.4"
          #echo ::set-output name=VERSION::"$(git rev-parse --short HEAD)-$(date --utc +'%Y%m%d%H%M')"
          #echo "::set-output name=GITHASH::$(git rev-parse --short HEAD)"
          #echo "::set-output name=BUILDDATE::$(date -u +"%Y%m%d%H%M")"
          echo  ::set-output name=CTAG::"2.34.4-mar20-23-patch2"
    - name: Build
      run: ./gradlew --no-daemon echo-web:installDist -x test
    - name: Login to Quay
          #if: startsWith(github.repository, ‘yugaa22/‘)
      uses: docker/login-action@v1
        # use service account flow defined at: https://github.com/docker/login-action#service-account-based-authentication-1
      with:
        registry: ${{ secrets.IMAGE_REPOSITRY }}
        username: ${{ secrets.IMAGE_USERNAME }}
        password: ${{ secrets.IMAGE_PASSWORD }}
    - name: dockerBuildpush
      uses: docker/build-push-action@v2
      with:
         context: .
         file: docker/ubi8/Dockerfile-fips
         push: true
         tags: |
           "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}-${{ steps.build_variables.outputs.CTAG }}"
    - id: get-build-name
      run: |
            imageName=${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}-${{ steps.build_variables.outputs.CTAG }}
            echo "oes=$imageName" >> $GITHUB_OUTPUT
